[package]
name = "simple_chatter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
rand = "0.8.5"
serde = "1.0.167"
serde_json = "1.0.100"